export const APP_CONSTANTS = {
  DEFAULT_PAGE: 1,
  DEFAULT_PAGE_LIMIT: 20,
  MAX_PAGE_LIMIT: 100,
  DEFAULT_SEARCH_RADIUS_KM: 10,
  MAX_SEARCH_RADIUS_KM: 50,
  DEFAULT_CURRENCY: 'EGP',
  EARTH_RADIUS_KM: 6371,
} as const;
